In [25]:
import xarray as xr

file = r"E:\glacier_research\datasets\era5_land_nepal_climate_1990-2026\data_stream-moda.nc"

with xr.open_dataset(file) as dataset:
    ds = dataset.load()

print(ds)

<xarray.Dataset> Size: 3GB
Dimensions:     (valid_time: 453, latitude: 235, longitude: 443)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 4kB 1989-01-01 ... 2026-09-01
    expver      (valid_time) <U4 7kB '0001' '0001' '0001' ... '0005' '0005'
  * latitude    (latitude) float64 2kB 39.3 39.2 39.1 39.0 ... 16.1 16.0 15.9
  * longitude   (longitude) float64 4kB 60.8 60.9 61.0 ... 104.8 104.9 105.0
    number      int64 8B 0
Data variables: (12/15)
    t2m         (valid_time, latitude, longitude) float32 189MB 272.8 ... 298.8
    snowc       (valid_time, latitude, longitude) float32 189MB 8.307 ... 0.0
    sde         (valid_time, latitude, longitude) float32 189MB 0.008789 ... ...
    sd          (valid_time, latitude, longitude) float32 189MB 0.001336 ... ...
    sf          (valid_time, latitude, longitude) float32 189MB 0.000274 ... 0.0
    smlt        (valid_time, latitude, longitude) float32 189MB 0.0002413 ......
    ...          ...
    es          (valid_time, latitude, longitude) float32 189MB -2.263e-05 .....
    sro         (valid_time, latitude, longitude) float32 189MB 1.527e-06 ......
    e           (valid_time, latitude, longitude) float32 189MB -0.0002327 .....
    u10         (valid_time, latitude, longitude) float32 189MB -0.3718 ... -...
    v10         (valid_time, latitude, longitude) float32 189MB 0.06652 ... 0...
    tp          (valid_time, latitude, longitude) float32 189MB 0.0004003 ......
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-10-26T04:17 GRIB to CDM+CF via cfgrib-0.9.1...

In [26]:
print(ds.data_vars)

Data variables:
    t2m      (valid_time, latitude, longitude) float32 189MB 272.8 ... 298.8
    snowc    (valid_time, latitude, longitude) float32 189MB 8.307 8.137 ... 0.0
    sde      (valid_time, latitude, longitude) float32 189MB 0.008789 ... -7....
    sd       (valid_time, latitude, longitude) float32 189MB 0.001336 ... -7....
    sf       (valid_time, latitude, longitude) float32 189MB 0.000274 ... 0.0
    smlt     (valid_time, latitude, longitude) float32 189MB 0.0002413 ... 0.0
    ssr      (valid_time, latitude, longitude) float32 189MB 5.964e+06 ... 1....
    str      (valid_time, latitude, longitude) float32 189MB -5.198e+06 ... -...
    ro       (valid_time, latitude, longitude) float32 189MB 1.531e-06 ... 0....
    es       (valid_time, latitude, longitude) float32 189MB -2.263e-05 ... 0.0
    sro      (valid_time, latitude, longitude) float32 189MB 1.527e-06 ... 0....
    e        (valid_time, latitude, longitude) float32 189MB -0.0002327 ... -...
    u10      (valid_time, latitude, longitude) float32 189MB -0.3718 ... -0.4406
    v10      (valid_time, latitude, longitude) float32 189MB 0.06652 ... 0.2804
    tp       (valid_time, latitude, longitude) float32 189MB 0.0004003 ... 0....

In [27]:
print(ds["tp"])

<xarray.DataArray 'tp' (valid_time: 453, latitude: 235, longitude: 443)> Size: 189MB
array([[[4.00310935e-04, 3.86274041e-04, 3.74226453e-04, ...,
         1.67554812e-04, 1.63002507e-04, 1.58502356e-04],
        [3.70299997e-04, 3.56538774e-04, 3.45698179e-04, ...,
         1.74245433e-04, 1.70460538e-04, 1.66653292e-04],
        [3.77929391e-04, 3.66135122e-04, 3.56248202e-04, ...,
         1.72427492e-04, 1.70833067e-04, 1.69417457e-04],
        ...,
        [           nan,            nan,            nan, ...,
         2.48691620e-04, 2.30013029e-04, 2.42239432e-04],
        [           nan,            nan,            nan, ...,
         2.52282800e-04, 2.50420155e-04, 2.63160648e-04],
        [           nan,            nan,            nan, ...,
         2.54853250e-04, 2.71058263e-04, 2.80662061e-04]],

       [[1.46750463e-04, 1.48464096e-04, 1.50065971e-04, ...,
         1.75211680e-04, 1.86938894e-04, 1.99373913e-04],
        [1.43785132e-04, 1.45871294e-04, 1.47897852e-04, ...,
         1.76902962e-04, 1.94329870e-04, 2.13164938e-04],
        [1.42950666e-04, 1.41639364e-04, 1.40052391e-04, ...,
         1.74466622e-04, 1.93905187e-04, 2.14856220e-04],
...
         9.94637609e-03, 1.02313906e-02, 1.07298046e-02],
        [           nan,            nan,            nan, ...,
         1.00562871e-02, 1.03847086e-02, 1.08794868e-02],
        [           nan,            nan,            nan, ...,
         1.03123337e-02, 1.06694400e-02, 1.11472607e-02]],

       [[2.72345533e-05, 2.79945125e-05, 2.85458555e-05, ...,
         3.93482740e-04, 4.05142899e-04, 4.15052171e-04],
        [2.63777365e-05, 2.55283703e-05, 2.61169662e-05, ...,
         4.26503713e-04, 4.25758655e-04, 4.39721043e-04],
        [2.65192975e-05, 2.40308036e-05, 2.38743414e-05, ...,
         4.16579540e-04, 4.14612587e-04, 4.05582483e-04],
        ...,
        [           nan,            nan,            nan, ...,
         1.38737066e-02, 1.40510229e-02, 1.43678961e-02],
        [           nan,            nan,            nan, ...,
         1.36821298e-02, 1.37711717e-02, 1.43917901e-02],
        [           nan,            nan,            nan, ...,
         1.34290336e-02, 1.35715632e-02, 1.41328229e-02]]],
      shape=(453, 235, 443), dtype=float32)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 4kB 1989-01-01 ... 2026-09-01
    expver      (valid_time) <U4 7kB '0001' '0001' '0001' ... '0005' '0005'
  * latitude    (latitude) float64 2kB 39.3 39.2 39.1 39.0 ... 16.1 16.0 15.9
  * longitude   (longitude) float64 4kB 60.8 60.9 61.0 ... 104.8 104.9 105.0
    number      int64 8B 0
Attributes: (12/31)
    GRIB_paramId:                             228
    GRIB_dataType:                            fc
    GRIB_numberOfPoints:                      104105
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_gridType:                            regular_ll
    ...                                       ...
    GRIB_totalNumber:                         0
    GRIB_units:                               m
    long_name:                                Total precipitation
    units:                                    m
    standard_name:                            unknown
    GRIB_surface:                             0.0

In [28]:
df = ds.to_dataframe().reset_index()

print(df.tail())

         valid_time  latitude  longitude         t2m  snowc           sde  \
47159560 2026-09-01      15.9      104.6  299.101562    0.0 -7.345365e-24
47159561 2026-09-01      15.9      104.7  298.998047    0.0 -7.345365e-24
47159562 2026-09-01      15.9      104.8  298.894531    0.0 -7.345365e-24
47159563 2026-09-01      15.9      104.9  298.826172    0.0 -7.345365e-24
47159564 2026-09-01      15.9      105.0  298.830078    0.0 -7.345365e-24

                    sd   sf  smlt         ssr        str        ro   es  \
47159560 -7.345365e-25  0.0   0.0  11888162.0 -2528223.0  0.009449  0.0
47159561 -7.345365e-25  0.0   0.0  11681280.0 -2459660.0  0.008948  0.0
47159562 -7.345365e-25  0.0   0.0  11450192.0 -2385459.0  0.009976  0.0
47159563 -7.345365e-25  0.0   0.0  11428744.0 -2319133.0  0.009912  0.0
47159564 -7.345365e-25  0.0   0.0  11394832.0 -2370627.0  0.010634  0.0

               sro         e       u10       v10        tp  number expver
47159560  0.002638 -0.003395 -0.441592  0.265291  0.013174       0   0005
47159561  0.004634 -0.003385 -0.439639  0.264803  0.013346       0   0005
47159562  0.001239 -0.003376 -0.442569  0.269197  0.013429       0   0005
47159563  0.001282 -0.003517 -0.444522  0.274080  0.013572       0   0005
47159564  0.001256 -0.003390 -0.440616  0.280428  0.014133       0   0005

In [29]:
import xarray as xr

files = [
    r"E:\glacier_research\datasets\era5_land_nepal_climate_1990-2026\data_stream-moda.nc",
    r"E:\glacier_research\datasets\era5_land_nepal_climate_1990-2026\geo.area-subset.39.3.105.15.9.60.8.nc",
    r"E:\glacier_research\datasets\era5_land_nepal_climate_1990-2026\cicecap.area-subset.39.3.105.15.9.60.8.nc"
]

In [30]:
print(xr.open_dataset(files[0]))

<xarray.Dataset> Size: 3GB
Dimensions:     (valid_time: 453, latitude: 235, longitude: 443)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 4kB 1989-01-01 ... 2026-09-01
    expver      (valid_time) <U4 7kB ...
  * latitude    (latitude) float64 2kB 39.3 39.2 39.1 39.0 ... 16.1 16.0 15.9
  * longitude   (longitude) float64 4kB 60.8 60.9 61.0 ... 104.8 104.9 105.0
    number      int64 8B ...
Data variables: (12/15)
    t2m         (valid_time, latitude, longitude) float32 189MB ...
    snowc       (valid_time, latitude, longitude) float32 189MB ...
    sde         (valid_time, latitude, longitude) float32 189MB ...
    sd          (valid_time, latitude, longitude) float32 189MB ...
    sf          (valid_time, latitude, longitude) float32 189MB ...
    smlt        (valid_time, latitude, longitude) float32 189MB ...
    ...          ...
    es          (valid_time, latitude, longitude) float32 189MB ...
    sro         (valid_time, latitude, longitude) float32 189MB ...
    e           (valid_time, latitude, longitude) float32 189MB ...
    u10         (valid_time, latitude, longitude) float32 189MB ...
    v10         (valid_time, latitude, longitude) float32 189MB ...
    tp          (valid_time, latitude, longitude) float32 189MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-10-26T04:17 GRIB to CDM+CF via cfgrib-0.9.1...

In [31]:
print(xr.open_dataset(files[1]))

<xarray.Dataset> Size: 836kB
Dimensions:    (time: 1, latitude: 235, longitude: 443)
Coordinates:
  * time       (time) datetime64[ns] 8B 2013-08-09T12:00:00
  * latitude   (latitude) float32 940B 39.3 39.2 39.1 39.0 ... 16.1 16.0 15.9
  * longitude  (longitude) float32 2kB 60.8 60.9 61.0 61.1 ... 104.8 104.9 105.0
Data variables:
    z          (time, latitude, longitude) float64 833kB ...
Attributes:
    Conventions:               CF-1.6
    history:                   Fri Jun 12 14:41:56 2020: ncpdq -U geo_1279l4_...
    NCO:                       4.7.2
    nco_openmp_thread_number:  1

In [32]:
print(xr.open_dataset(files[2]))

<xarray.Dataset> Size: 836kB
Dimensions:    (time: 1, latitude: 235, longitude: 443)
Coordinates:
  * time       (time) datetime64[ns] 8B 2013-01-25
  * latitude   (latitude) float32 940B 39.3 39.2 39.1 39.0 ... 16.1 16.0 15.9
  * longitude  (longitude) float32 2kB 60.8 60.9 61.0 61.1 ... 104.8 104.9 105.0
Data variables:
    glm        (time, latitude, longitude) float64 833kB ...
Attributes:
    CDI:          Climate Data Interface version 2.5.1 (https://mpimet.mpg.de...
    Conventions:  CF-1.6
    history:      Mon Oct  6 10:55:26 2025: ncrename -H -O -v si10,glm ciceca...
    CDO:          Climate Data Operators version 2.5.1 (https://mpimet.mpg.de...
    NCO:          netCDF Operators version 5.3.2 (Homepage = http://nco.sf.ne...

In [33]:
from pathlib import Path

import pandas as pd
import xarray as xr
from IPython.display import display

DATA_DIR = Path(r"E:\glacier_research\datasets\era5_land_nepal_climate_1990-2026")
OUTPUT_DIR = Path(r"E:\glacier_research\datasets_to_csv\era5_land_nepal_climate_1990-2026_csv")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FILES = {
    "data_stream-moda": DATA_DIR / "data_stream-moda.nc",
    "geo": DATA_DIR / "geo.area-subset.39.3.105.15.9.60.8.nc",
    "cicecap": DATA_DIR / "cicecap.area-subset.39.3.105.15.9.60.8.nc",
}

# One row per timestamp/grid-cell, with coordinates and variables as columns.
dataframes = {}
for name, path in FILES.items():
    with xr.open_dataset(path) as dataset:
        dataframes[name] = dataset.to_dataframe().reset_index()

pd.set_option("display.max_columns", None)

for name, dataframe in dataframes.items():
    print(f"{name}: {dataframe.shape[0]:,} rows x {dataframe.shape[1]} columns")
    display(dataframe)

data_stream-moda: 47,159,565 rows x 20 columns

,valid_time,latitude,longitude,t2m,snowc,sde,sd,sf,smlt,ssr,str,ro,es,sro,e,u10,v10,tp,number,expver
0,1989-01-01,39.3,60.8,272.763611,8.306641,8.789062e-03,1.336098e-03,0.000274,0.000241,5963792.0,-5198349.0,0.000002,-0.000023,0.000002,-0.000233,-0.371769,0.066521,0.000400,0,0001
1,1989-01-01,39.3,60.9,272.736267,8.136719,8.789062e-03,1.307487e-03,0.000265,0.000234,5933516.0,-5189179.0,0.000001,-0.000022,0.000001,-0.000233,-0.362003,0.052361,0.000386,0,0001
2,1989-01-01,39.3,61.0,272.726501,8.019531,8.789062e-03,1.288414e-03,0.000257,0.000227,5927384.0,-5184761.0,0.000001,-0.000022,0.000001,-0.000229,-0.357609,0.025505,0.000374,0,0001
3,1989-01-01,39.3,61.1,272.726501,7.847656,7.812500e-03,1.260757e-03,0.000249,0.000221,5919832.0,-5185551.0,0.000001,-0.000022,0.000001,-0.000227,-0.353214,-0.000374,0.000362,0,0001
4,1989-01-01,39.3,61.2,272.730408,7.675781,7.812500e-03,1.235008e-03,0.000241,0.000214,5907550.0,-5186547.0,0.000001,-0.000021,0.000001,-0.000230,-0.343937,-0.014046,0.000352,0,0001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47159560,2026-09-01,15.9,104.6,299.101562,0.000000,-7.345365e-24,-7.345365e-25,0.000000,0.000000,11888162.0,-2528223.0,0.009449,0.000000,0.002638,-0.003395,-0.441592,0.265291,0.013174,0,0005
47159561,2026-09-01,15.9,104.7,298.998047,0.000000,-7.345365e-24,-7.345365e-25,0.000000,0.000000,11681280.0,-2459660.0,0.008948,0.000000,0.004634,-0.003385,-0.439639,0.264803,0.013346,0,0005
47159562,2026-09-01,15.9,104.8,298.894531,0.000000,-7.345365e-24,-7.345365e-25,0.000000,0.000000,11450192.0,-2385459.0,0.009976,0.000000,0.001239,-0.003376,-0.442569,0.269197,0.013429,0,0005
47159563,2026-09-01,15.9,104.9,298.826172,0.000000,-7.345365e-24,-7.345365e-25,0.000000,0.000000,11428744.0,-2319133.0,0.009912,0.000000,0.001282,-0.003517,-0.444522,0.274080,0.013572,0,0005
47159564,2026-09-01,15.9,105.0,298.830078,0.000000,-7.345365e-24,-7.345365e-25,0.000000,0.000000,11394832.0,-2370627.0,0.010634,0.000000,0.001256,-0.003390,-0.440616,0.280428,0.014133,0,0005

geo: 104,105 rows x 4 columns

                      time   latitude   longitude            z
0      2013-08-09 12:00:00  39.299999   60.799999  1341.438355
1      2013-08-09 12:00:00  39.299999   60.900002  1385.636423
2      2013-08-09 12:00:00  39.299999   61.000000  1401.708448
3      2013-08-09 12:00:00  39.299999   61.099998  1405.726454
4      2013-08-09 12:00:00  39.299999   61.200001  1415.771470
...                    ...        ...         ...          ...
104100 2013-08-09 12:00:00  15.900000  104.599998  1529.280145
104101 2013-08-09 12:00:00  15.900000  104.699997  1661.874349
104102 2013-08-09 12:00:00  15.900000  104.800003  1781.410033
104103 2013-08-09 12:00:00  15.900000  104.900002  1775.383024
104104 2013-08-09 12:00:00  15.900000  105.000000  1715.112931

[104105 rows x 4 columns]

cicecap: 104,105 rows x 4 columns

             time   latitude   longitude  glm
0      2013-01-25  39.299999   60.799999  0.0
1      2013-01-25  39.299999   60.900002  0.0
2      2013-01-25  39.299999   61.000000  0.0
3      2013-01-25  39.299999   61.099998  0.0
4      2013-01-25  39.299999   61.200001  0.0
...           ...        ...         ...  ...
104100 2013-01-25  15.900000  104.599998  0.0
104101 2013-01-25  15.900000  104.699997  0.0
104102 2013-01-25  15.900000  104.800003  0.0
104103 2013-01-25  15.900000  104.900002  0.0
104104 2013-01-25  15.900000  105.000000  0.0

[104105 rows x 4 columns]

In [35]:
# Save all three DataFrames as CSV files
for name, dataframe in dataframes.items():
    output_file = OUTPUT_DIR / f"{name}.csv"
    dataframe.to_csv(output_file, index=False)
    print(f"Saved: {output_file}")

Saved: E:\glacier_research\datasets_to_csv\era5_land_nepal_climate_1990-2026_csv\data_stream-moda.csv
Saved: E:\glacier_research\datasets_to_csv\era5_land_nepal_climate_1990-2026_csv\geo.csv
Saved: E:\glacier_research\datasets_to_csv\era5_land_nepal_climate_1990-2026_csv\cicecap.csv

In [36]:
import pandas as pd

df = pd.read_csv(r"E:\glacier_research\datasets_to_csv\era5_land_nepal_climate_1990-2026_csv\data_stream-moda.csv")
df.tail()

,valid_time,latitude,longitude,t2m,snowc,sde,sd,sf,smlt,ssr,str,ro,es,sro,e,u10,v10,tp,number,expver
47159560,2026-09-01,15.9,104.6,299.10156,0.0,-7.345365e-24,-7.345365e-25,0.0,0.0,11888162.0,-2528223.0,0.009449,0.0,0.002638,-0.003395,-0.441592,0.265291,0.013174,0,5
47159561,2026-09-01,15.9,104.7,298.99805,0.0,-7.345365e-24,-7.345365e-25,0.0,0.0,11681280.0,-2459660.0,0.008948,0.0,0.004634,-0.003385,-0.439639,0.264803,0.013346,0,5
47159562,2026-09-01,15.9,104.8,298.89453,0.0,-7.345365e-24,-7.345365e-25,0.0,0.0,11450192.0,-2385459.0,0.009976,0.0,0.001239,-0.003376,-0.442569,0.269197,0.013429,0,5
47159563,2026-09-01,15.9,104.9,298.82617,0.0,-7.345365e-24,-7.345365e-25,0.0,0.0,11428744.0,-2319133.0,0.009912,0.0,0.001282,-0.003517,-0.444522,0.274080,0.013572,0,5
47159564,2026-09-01,15.9,105.0,298.83008,0.0,-7.345365e-24,-7.345365e-25,0.0,0.0,11394832.0,-2370627.0,0.010634,0.0,0.001256,-0.003390,-0.440616,0.280428,0.014133,0,5